packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # exclude packages that are inside test directories
  - "!**/test/**"
## Using catalogs: https://pnpm.io/catalogs

## Defining a default a catalog
# catalog:
#   chalk: ^4.1.2

## Defining (multiple) named catalogs
# catalogs:
#   react16:
#     react: ^16.7.0
#     react-dom: ^16.7.0
#   react17:
#     react: ^17.10.0
#     react-dom: ^17.10.0
