#!/usr/bin/env zsh

RAILS_ENV="${RAILS_ENV:-development}"
# Working script for creating a PostgreSQL database dump for the primary
# database of the CAMI Rails application.
BACKUP_PATH="packages/twenty-crm/data/${RAILS_ENV}/postgres/downloads"
mkdir -p "$BACKUP_PATH"
MOUNTED_BACKUP_PATH="/usr/local/downloads"
BACKUP_FILE="${MOUNTED_BACKUP_PATH}/twenty-crm-$(date +'%Y%m%d.%H%M%S%z').dump"
DBUSER="${PG_DATABASE_USER:-postgres}"
DBNAME="${PG_DATABASE_NAME:-default}"

exec "$SCRIPT_DIR/create-db-role-for-local-user"

cat <<-EOF
[Local user]:         $USER
[Postgres username]:  $DBUSER
[Database name]:      $DBNAME
[Backup file]:        $BACKUP_FILE
EOF

# Dump CRM database
docker exec -it twenty-db-1 pg_dump --format=c --no-owner \
  --no-privileges --verbose --encoding=UTF-8 \
  --username "$DBUSER" --host 127.0.0.1  \
  --file "$BACKUP_FILE" $DBNAME
